"""empty message

Revision ID: 191db4bfb034
Revises: d064814def5c
Create Date: 2020-12-12 14:50:11.171862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '191db4bfb034'
down_revision = 'd064814def5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_info', 'lon')
    op.drop_column('restaurant_info', 'lat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_info', sa.Column('lat', mysql.FLOAT(precision=16, scale=16), nullable=True))
    op.add_column('restaurant_info', sa.Column('lon', mysql.FLOAT(precision=16, scale=16), nullable=True))
    # ### end Alembic commands ###
