"""empty message

Revision ID: d064814def5c
Revises: 016cbe128947
Create Date: 2020-12-12 14:47:51.055360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd064814def5c'
down_revision = '016cbe128947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_info', sa.Column('lat', sa.Float(precision='16,16'), nullable=True))
    op.add_column('restaurant_info', sa.Column('lon', sa.Float(precision='16,16'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_info', 'lon')
    op.drop_column('restaurant_info', 'lat')
    # ### end Alembic commands ###
