"""empty message

Revision ID: ee0a4c1a4c25
Revises: 191db4bfb034
Create Date: 2020-12-12 14:50:27.943453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0a4c1a4c25'
down_revision = '191db4bfb034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_info', sa.Column('lat', sa.Float(precision='20,16'), nullable=True))
    op.add_column('restaurant_info', sa.Column('lon', sa.Float(precision='20,16'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_info', 'lon')
    op.drop_column('restaurant_info', 'lat')
    # ### end Alembic commands ###
